Apply some fixes to WDL examples
openwdl/wdl pull request #689
Opened 2024-11-01 00:14 UTC by stxue1

These are fixes for some of the comments I left at #669 

I'm merging into `wdl-1.1.3` instead so the eventual merge into `wdl-1.1` by #669 will be cleaner.

There are only two tests left that don't work: `hisat2` and `gatk_haplotype_caller`. I haven't look at them yet as I don't have much experience with running the hisat2 or gatk pipeline.

Other than those two, I believe the rest of the examples work.

### Checklist
- [ ] Pull request details were added to CHANGELOG.md
- [ ] Valid examples WDL's were added or updated to the SPEC.md (see the [guide](https://github.com/openwdl/wdl-tests/blob/main/docs/MarkdownTests.md) on writing markdown tests)

2025-01-14 05:48 UTC, claymcleod commented on SPEC.md
> -  "test_hints.num_lines": 3
It looks like [`greetings.txt`](https://github.com/openwdl/wdl-tests/blob/main/spec/wdl-1.1/data/greetings.txt) has 3 lines.

2025-01-14 05:55 UTC, claymcleod requested changes
Otherwise looks good to me.

2025-01-23 21:47 UTC, stxue1 commented on SPEC.md
> -  "test_hints.num_lines": 3
Running `wc -l` on the file returns 2 since wc counts the number of newline characters, so I think 2 is correct here.

2025-01-23 21:55 UTC, claymcleod commented on SPEC.md
> -  "test_hints.num_lines": 3
It appears you're correct, today I learned something new.

2025-01-23 21:56 UTC, merged