[WIP] `README.md` cleanup, content reorganization
openwdl/wdl pull request #691
Opened 2024-11-17 15:25 UTC by claymcleod

This pull request cleans up the `README.md` significantly and pushes much of it's information to the website (a PR is forthcoming on that). The idea is that content should only live in one place—not be duplicated between the `README.md` and the website.

I also took the liberty of selecting a font for the `README.md` header, which is, in some ways, a suggestion for a font for assets from the project as a whole. In this case, I chose [Metropolis](https://github.com/dw5/metropolis), which is made available under the UNLICENSE.

### Checklist
- [ ] Pull request details were added to CHANGELOG.md
- [ ] Valid examples WDL's were added or updated to the SPEC.md (see the [guide](https://github.com/openwdl/wdl-tests/blob/main/docs/MarkdownTests.md) on writing markdown tests)

2024-11-17 15:38 UTC, claymcleod commented
I also took a shot at updating some of the colors. I'm not sure if I like that yet. Here are some more options using close to the existing colors.

![README Logo-CYAN](https://github.com/user-attachments/assets/8cdb2f53-699f-46de-b49d-d16c4272fa99)

2025-01-11 20:33 UTC, claymcleod commented
I ended up just using the existing colors as I showed in the examples above. This should now be ready for review.

2025-01-13 21:16 UTC, jdidion requested changes
Mostly looks good - thanks for the revision @claymcleod!

2025-01-13 21:16 UTC, jdidion commented on README.md
> +human-readable/writeable syntax. It introduces a domain-specific language that aims to
We adopted the convention of one sentence per line to make PRs smaller/reviews easier.

2025-01-13 21:16 UTC, jdidion commented on README.md
> +on ease of implementation and accessibility to wide range of users, including software
```suggestion
on ease of implementation and accessibility to a wide range of users, including software
```

2025-01-13 21:16 UTC, jdidion commented on README.md
> +expressed. Last, the language is driven and developed by community of distributed
```suggestion
expressed. Last, the language is driven and developed by a community of distributed
```

2025-01-13 21:16 UTC, jdidion commented on README.md
> +volunteers as an open standard—there is no single execution engine, and anyone can build
```suggestion
volunteers as an open standard; there is no single execution engine, and anyone can build
```

2025-01-13 21:16 UTC, jdidion commented on README.md
> +If you're new to WDL, welcome 👋—we _highly_ recommend you read the [getting started
```suggestion
If you're new to WDL, welcome 👋. We _highly_ recommend that you read the [getting started
```

2025-01-13 21:16 UTC, jdidion commented on README.md
> +documentation][wdl-docs] to learn how to write workflows. Beyond that, here are some
```suggestion
documentation][wdl-docs] to learn how to write tasks and workflows. Beyond that, here are some
```

2025-01-13 21:16 UTC, jdidion commented on README.md
> +documentation][wdl-docs] to learn how to write workflows. Beyond that, here are some
I don't think the sentence starting "Beyond that..." is necessary as there's really only one sub-section ("Join the community"). I also don't think the "Conclusion" section is necessary.

2025-01-13 23:42 UTC, claymcleod commented on README.md
> +human-readable/writeable syntax. It introduces a domain-specific language that aims to
Sounds good, will do.

2025-01-14 01:37 UTC, claymcleod commented
@jdidion I think everything has been addressed here.

2025-01-22 19:55 UTC, jdidion approved these changes
Looks great!

2025-01-23 05:04 UTC, claymcleod commented
Note that I plan to make further changes to the fonts, etc, in the future. For now, I'll merge this in as it's a big improvement.

2025-01-23 05:04 UTC, merged